<?php

namespace App\Services;

use Carbon\Carbon;
use Carbon\CarbonInterface;

/**
 * Parses lead export .txt files generated by {@see \App\Http\Controllers\LeadController::buildLeadTxtPayload}.
 */
final class LeadTxtExportParser
{
    /**
     * Split a full file into one or more lead blocks (export may separate leads with a line of 70 dashes).
     *
     * @return array<int, array<string, mixed>>
     */
    public function parseFile(string $raw): array
    {
        $normalized = str_replace(["\r\n", "\r"], "\n", $raw);
        $normalized = preg_replace('/^\xEF\xBB\xBF/', '', $normalized) ?? $normalized;
        $parts = preg_split('/\n-{70}\n/', $normalized) ?: [];
        $out = [];
        foreach ($parts as $part) {
            $part = trim($part);
            if ($part === '') {
                continue;
            }
            $out[] = $this->parseLeadBlock($part);
        }

        return $out;
    }

    /**
     * @return array<string, mixed>
     */
    public function parseLeadBlock(string $text): array
    {
        $lines = preg_split('/\n/', str_replace("\r", '', $text)) ?: [];
        $lines = array_map(static fn (string $l): string => rtrim($l, "\r\n"), $lines);

        $i = 0;
        $n = count($lines);

        $get = function (int $idx) use ($lines): string {
            return $lines[$idx] ?? '';
        };

        $skipBlanks = function () use (&$i, $n, $get): void {
            while ($i < $n && trim($get($i)) === '') {
                $i++;
            }
        };

        // Strict line order as exported; always consume the line so we cannot get stuck.
        $expectLabel = function (string $label) use (&$i, $n, $get): string {
            if ($i >= $n) {
                return '';
            }
            $line = $get($i);
            $i++;
            $value = $this->lineValueAfterLabel($line, $label);

            return $value !== null ? $value : '';
        };

        $skipBlanks();

        // Header (same order as buildLeadTxtPayload)
        $fullName = $expectLabel('Name');
        [$firstName, $lastName] = $this->splitFullName($fullName);
        $phones = [
            $expectLabel('Phone'),
            $expectLabel('Alt Phone'),
            $expectLabel('Phone 3'),
            $expectLabel('Phone 4'),
            $expectLabel('Phone 5'),
        ];
        $address = $expectLabel('Add');
        $dobRaw = $expectLabel('Dob');
        $mmn = $expectLabel('Mmn');
        $ssn = $expectLabel('Ssn');
        $email = $expectLabel('Email');

        $skipBlanks();

        // Comment block
        $details = '';
        if ($i < $n && preg_match('/^Comment\s*:\s*(.*)$/i', $get($i), $m)) {
            $commentLines = [$m[1]];
            $i++;
            while ($i < $n) {
                $line = $get($i);
                if (preg_match('/^\s*BN\s*:/i', $line) || preg_match('/^\s*Tdebt\s*:/i', $line)) {
                    break;
                }
                if (trim($line) === '' && $i + 1 < $n && preg_match('/^\s*BN\s*:/i', $get($i + 1))) {
                    $i++;
                    break;
                }
                $commentLines[] = $line;
                $i++;
            }
            $details = implode("\n", $commentLines);
        }

        $skipBlanks();

        // Cards
        $cards = [];
        while ($i < $n && preg_match('/^\s*BN\s*:\s*(.*)$/i', $get($i), $m)) {
            $card = [
                'bank_name' => trim($m[1]),
                'charge_card' => stripos($m[1], 'Charge Card') !== false,
                'name_on_card' => '',
                'bank_tollfree' => '',
                'card_number' => '',
                'card_expiry' => '',
                'card_cvc' => '',
                'balance' => null,
                'available_amount' => null,
                'last_payment' => '',
                'due_payment' => '',
                'apr' => null,
                'comment' => '',
                'fees' => null,
            ];
            $i++;
            $card['name_on_card'] = $this->requireLabelLine($lines, $i, 'Card holder name');
            $card['bank_tollfree'] = $this->requireLabelLine($lines, $i, 'BT');
            $card['card_number'] = $this->requireLabelLine($lines, $i, 'CC');
            $card['card_expiry'] = $this->requireLabelLine($lines, $i, 'Exp');
            $card['card_cvc'] = $this->requireLabelLine($lines, $i, 'Cvc');
            // optional blank
            if ($i < $n && trim($get($i)) === '') {
                $i++;
            }
            $card['balance'] = $this->parseMoney($this->requireLabelLine($lines, $i, 'Bal'));
            $card['available_amount'] = $this->parseMoney($this->requireLabelLine($lines, $i, 'Av'));
            $card['last_payment'] = $this->requireLabelLine($lines, $i, 'Lp');
            $card['due_payment'] = $this->requireLabelLine($lines, $i, 'Dp');
            $card['apr'] = $this->parseMoney($this->requireLabelLine($lines, $i, 'Apr'));
            $card['comment'] = $this->requireLabelLine($lines, $i, 'Comment');
            $card['fees'] = $this->parseMoney($this->requireLabelLine($lines, $i, 'Fees'));
            $cards[] = $card;
            if ($i < $n && trim($get($i)) === '') {
                $i++;
            }
            $skipBlanks();
        }

        $tdebt = null;
        $tcards = null;
        $chargeAmount = null;

        if ($i < $n && preg_match('/^\s*Tdebt\s*:\s*(.*)$/i', $get($i), $m)) {
            $tdebt = $this->parseMoney(trim($m[1]));
            $i++;
        }
        if ($i < $n && preg_match('/^\s*Tcards\s*:\s*(.*)$/i', $get($i), $m)) {
            $tcards = (int) preg_replace('/\D/', '', $m[1]);
            $i++;
        }
        if ($i < $n && preg_match('/^\s*Charge Amount\s*:\s*(.*)$/i', $get($i), $m)) {
            $chargeAmount = $this->parseMoney(trim($m[1]));
            $i++;
        }
        // Deal : (ignored)

        $dob = $this->parseDob($dobRaw);

        $approxDebt = $tdebt;
        if ($approxDebt === null && $cards !== []) {
            $sum = 0.0;
            foreach ($cards as $c) {
                $sum += (float) ($c['balance'] ?? 0);
            }
            $approxDebt = $sum > 0 ? round($sum, 2) : null;
        }

        $fees = $chargeAmount;
        if ($fees === null && $cards !== []) {
            $sum = 0.0;
            foreach ($cards as $c) {
                $sum += (float) ($c['fees'] ?? 0);
            }
            $fees = $sum > 0 ? round($sum, 2) : null;
        }

        return [
            'first_name' => $firstName,
            'last_name' => $lastName,
            'phones' => array_values(array_filter(array_map('trim', $phones), fn ($p) => $p !== '')),
            'address' => $address !== '' ? $address : null,
            'date_of_birth' => $dob,
            'mothers_maiden_name' => $mmn !== '' ? $mmn : null,
            'ssn' => $ssn !== '' ? $ssn : null,
            'email' => $email !== '' ? $email : null,
            'details' => $details !== '' ? $details : null,
            'approx_debt' => $approxDebt,
            'fees' => $fees,
            'cards' => $cards,
            'meta' => [
                'tcards' => $tcards,
            ],
        ];
    }

    private function lineValueAfterLabel(string $line, string $label): ?string
    {
        $pattern = '/^' . preg_quote($label, '/') . '\s*:\s*(.*)$/iu';

        return preg_match($pattern, $line, $m) ? $m[1] : null;
    }

    /**
     * @param array<int, string> $lines
     */
    private function requireLabelLine(array $lines, int &$i, string $label): string
    {
        $line = $lines[$i] ?? '';
        $val = $this->lineValueAfterLabel($line, $label);
        if ($val !== null) {
            $i++;

            return $val;
        }
        $i++;

        return '';
    }

    private function splitFullName(string $full): array
    {
        $full = trim($full);
        if ($full === '') {
            return ['Unknown', 'Lead'];
        }
        $parts = preg_split('/\s+/', $full) ?: [];
        if (count($parts) === 1) {
            return [$parts[0], ''];
        }

        return [$parts[0], implode(' ', array_slice($parts, 1))];
    }

    private function parseDob(string $raw): ?CarbonInterface
    {
        $raw = trim($raw);
        if ($raw === '') {
            return null;
        }
        foreach (['m/d/Y', 'n/j/Y', 'Y-m-d'] as $fmt) {
            try {
                return Carbon::createFromFormat($fmt, $raw)->startOfDay();
            } catch (\Throwable) {
                // try next
            }
        }
        try {
            return Carbon::parse($raw)->startOfDay();
        } catch (\Throwable) {
            return null;
        }
    }

    private function parseMoney(string $raw): ?float
    {
        $raw = trim($raw);
        if ($raw === '') {
            return null;
        }
        $clean = preg_replace('/[^0-9.\-]/', '', str_replace(',', '', $raw)) ?? '';
        if ($clean === '' || $clean === '-' || $clean === '.') {
            return null;
        }

        return round((float) $clean, 2);
    }
}
